apps/licencias/urls.py
#! /usr/bin/python
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, include, url
from views import *

urlpatterns=patterns( '',  
  url(r'^$',  licencias, name='licencias'),

 )

rrhh/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rrhh.views.home', name='home'),
    # url(r'^rrhh/', include('rrhh.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'apps.accounts.views.login', name='login'),
    url(r'^$', 'apps.accounts.views.logout', name='logout'),
    url(r'^personal/', include('apps.personal.urls')),
    url(r'^referencias/', include('apps.referencias.urls')),
    url(r'^licencias/', include('apps.licencias.urls')),
)

apps/licencias/models.py
#! /usr/bin/python
# -*- encoding: utf-8 -*-|

from __future__ import unicode_literals
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import Group,Permission,User
from django.db.models import signals
from apps.referencias.models import *
from apps.personal.models import *

class Licencia(models.Model):
	personal 		= models.ForeignKey('personal.Personal',related_name='licencias',on_delete=models.PROTECT)
	codigo 			= models.ForeignKey('referencias.RefLicencia',on_delete=models.PROTECT)
	fecha_desde 	= models.DateField()
	cantidad_dias 	= models.IntegerField()
	fecha_hasta 	= models.DateField()
	observaciones 	= models.CharField(max_length = 150,blank =True, null =True)

	class Meta:
		unique_together = ('personal','codigo','fecha_desde','cantidad_dias')
		ordering 		= ['-fecha_desde']
		db_table		= 'Licencia'

apps/licencias/forms.py
#! /usr/bin/python
# -*- encoding: utf-8 -*-

from django import forms 
from apps.referencias.models import *
from apps.licencias.models import *
from django.forms import ModelForm, TimeField
from django.contrib import admin
from django.utils import timezone 
from django.conf import settings
from django.contrib.auth.models import  Group,Permission,User
from django.contrib.admin import widgets
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.forms.widgets import CheckboxSelectMultiple
from django.core.exceptions import ValidationError


class LicenciaForm(forms.ModelForm):
	personal	= forms.ModelChoiceField(widget=forms.Select(attrs=dict({'class':'select','required':'required'})),queryset=Personal.objects.filter(borrado=False),label="DNI Empleado")
	codigo		= forms.ModelChoiceField(widget=forms.Select(attrs=dict({'class':'select','required':'required'})),queryset=RefLicencia.objects.all(),label="Código de licencia")
	fecha_desde = forms.DateField(widget=forms.DateInput(attrs=dict({'class':'form-control input-block-level', 'placeholder':'Fecha inicio Licencia','required':'required','readonly':'readonly'})),required=True)
	cantidad_dias = forms.IntegerField(widget=forms.TextInput(attrs=dict({'class':'form-control input-block-level', 'placeholder':'Total de dias de Licencia','required':'required'})),required=True)
	fecha_hasta = forms.DateField(widget=forms.DateInput(attrs=dict({'class':'form-control input-block-level', 'placeholder':'Fecha de fin de la licencia','required':'required','readonly':'readonly'})),required=True)
	observaciones = forms.CharField(widget=forms.Textarea(attrs=dict({'class':'form-control input-block-level','rows':'4','cols':'50'})))

	def __init__(self, *args, **kwargs):
            super(ModelForm, self).__init__(*args, **kwargs)
            self.fields['fecha_desde'].widget.format = '%d/%m/%Y'
            self.fields['fecha_hasta'].widget.format = '%d/%m/%Y'
            # at the same time, set the input format on the date field like you want it:
            self.fields['fecha_desde'].input_formats = ['%d/%m/%Y']
            self.fields['fecha_hasta'].input_formats = ['%d/%m/%Y']

	class Meta:
		model = Licencia

apps/licencias/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template.loader import get_template
from django.template import Context, Template, RequestContext
from django.http import HttpResponseRedirect, HttpResponse, Http404
import datetime
from django.conf import settings
from django.template import RequestContext
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from datetime import datetime
from django.forms.forms import NON_FIELD_ERRORS
from forms import *
from models import *
from django.views.decorators.cache import cache_control
from django.core import serializers
from django.core.context_processors import csrf 

def licencias(request):
	if request.method == 'POST':
		form = LicenciaForm(request.POST)
		if form.is_valid():
			form.save()
	form 	 = LicenciaForm()
	lista = Licencia.objects.all()
	return render_to_response('licencia/formulario_licencia.html',{'form':form,'lista':lista},context_instance=RequestContext(request))

templates/licencia/formulario_licencia.html
{% extends 'base.html' %}


{% block cuerpo %}
<h3>Carga de licencias del Personal</h3>
<hr>
	<form role="form"  method="POST" action ="{% url 'licencias' %}">{% csrf_token %}	
		<div class="form-group">
			<label for="id_personal">DNI Empleado</label>{{form.personal}}
		</div>
		<div class="form-group">
			<label for="id_codigo">C&oacute;digo de Licencia</label>{{form.codigo}}
		</div>
		<div class="form-group">
			<label for="id_fecha_desde">Fecha desde</label>{{form.fecha_desde}}
		</div>
		<div class="form-group">
			<label for="id_cantidad_dias">Cantidad de dias</label>{{form.cantidad_dias}}
		</div>
		<div class="form-group">
			<label for="id_fecha_hasta">Fecha hasta</label>{{form.fecha_hasta}}<a href="#" class="btn btn-success btn-xs" id="calcula_fecha">Calcular</a>
		</div>
		<div class="form-group">
			<label for="observaciones">Observaciones</label>{{form.observaciones}}
		</div>
		<button type="submit" class="btn btn-info pull-right">Guardar</button>
	</form>
	<hr>
		<h4> <b>Listado General</b> </h4>
			<table class="table table-bordered table-condensed" id="table" name="table">
				<thead>
					<tr>
						<th>
							DNI
						</th>
						<th>
							Apellido y nombre
						</th>
						<th>
							Tipo Licencia
						</th>
						<th>
							Dias
						</th>
						<th>
							Desde
						</th>
						<th>
							Hasta
						</th>
					</tr>

				</thead>
				<tbody>
					{% for elemento in lista %}
						<tr>

							<td>
								{{elemento.personal.persona_id.nro_doc}}
							</td>
							<td>
								{{elemento.personal.persona_id.apellidos}}, {{elemento.personal.persona_id.nombres}}
							</td>
							<td>
								{{elemento.codigo}}
							</td>				
							<td>
								{{elemento.cantidad_dias}}
							</td>			
							<td>
								{{elemento.fecha_desde|date:"d/m/Y"}}
							</td>
							<td>
								{{elemento.fecha_hasta|date:"d/m/Y"}}
							</td>
							<!--td align="center">
								<a class="btn btn-xs btn-success" href="{% url 'editar_personal' elemento.id %}"> <i class="glyphicon glyphicon-edit"></i> Editar </a>
								<a class="btn btn-xs btn-danger" href="{% url 'remove_personal' elemento.id %}" onclick="return confirm('Por favor confirme que desea eliminar el registro.')"> <i class="glyphicon glyphicon-trash"></i> Eliminar </a>

							</td-->
						</tr>
					{% endfor %}
				</tbody>
			</table>
{% endblock cuerpo %}